name: "Change Request"
description: "SOC2-compliant change request template"
title: "[Change Request] <Short Description>"
labels: ["change-request", "pending-approval"]
assignees: []

body:
  - type: textarea
    id: summary
    attributes:
      label: Change Summary
      description: Describe the change, why it’s needed, and link related issues.
      placeholder: |
        **Description:** Update dependency X to version Y  
        **Reason:** Fixes security vulnerability CVE-XXXX  
        **Related Issues:** Closes #123
    validations:
      required: true

  - type: dropdown
    id: change_type
    attributes:
      label: Change Type
      options:
        - Standard (planned, tested)
        - Emergency (urgent, expedited)
    validations:
      required: true

  - type: checkboxes
    id: risk_impact
    attributes:
      label: Risk & Impact
      description: Review impact of this change
      options:
        - label: Reviewed for security impact
        - label: Reviewed for user/ops impact
        - label: No material impact identified

  - type: textarea
    id: impact_notes
    attributes:
      label: Impact Notes
      description: Short explanation of risks or components affected
      placeholder: "Minimal risk; affects only internal API"

  - type: checkboxes
    id: rollout_validation
    attributes:
      label: Rollout & Validation
      options:
        - label: Rollout plan documented
        - label: Rollback plan documented
        - label: Tested in staging/dev with evidence (screenshots/logs/links)

  - type: checkboxes
    id: approvals
    attributes:
      label: Approvals
      description: Required approvals before merge
      options:
        - label: Requester (engineer opening PR)
        - label: Team Lead
        - label: Security/CTO (if required)

  - type: input
    id: deployment_date
    attributes:
      label: Planned Deployment Date
      placeholder: "YYYY-MM-DD"

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Details
      description: Steps for implementation or link to rollout doc
      placeholder: "Deployment will be handled via workflow XYZ. See doc link: ..."

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Any other context for reviewers (links, diagrams, dashboards)
